### ISSUE TITLE
Facebook has same link as Instagram; Instagram's href is messed up

### ISSUE THREAD

**Issue by liam4** [JamCon/JamCon.github.io#1]
Just add `https://` before the `instagram.com` and it should be fixed (right now it goes to `jamcon.github.io/instagram.com/jamconmidwest`.

**Comment by aptitudex** [comment]
Hey, thanks! I actually ended up removing the two other social media links altogether, but thanks for the heads up :eyes:

**Comment by liam4** [comment]
Looks like this was fixed in https://github.com/JamCon/JamCon.github.io/commit/08232463bcbd9ab33caa0c75ab0c9ff2363eeaad.
